'use client';

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Star, Download, FileText, ImageIcon, File as FileIcon, Trash2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import { formatDistanceToNow } from 'date-fns';

export default function MyFilesPage() {
  const queryClient = useQueryClient();

  const { data: files = [], isLoading } = useQuery({
    queryKey: ['user_files'],
    queryFn: async () => {
      const res = await fetch('/api/v1/files');
      if (!res.ok) throw new Error('Failed to fetch files');
      return res.json();
    },
  });

  const toggleFavorite = useMutation({
    mutationFn: async ({ id, is_favorite }: { id: string; is_favorite: boolean }) => {
      const res = await fetch(`/api/v1/files/${id}/favorite`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ is_favorite }),
      });
      if (!res.ok) throw new Error('Failed to toggle favorite');
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['user_files'] });
    },
  });

  const deleteFile = useMutation({
    mutationFn: async (id: string) => {
      const res = await fetch(`/api/v1/files/${id}`, {
        method: 'DELETE',
      });
      if (!res.ok) throw new Error('Failed to delete file');
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['user_files'] });
    },
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-100">My Files</h1>
      </div>

      {isLoading ? (
        <div className="flex h-64 items-center justify-center">
          <div className="h-8 w-8 animate-spin rounded-full border-4 border-indigo-500 border-t-transparent"></div>
        </div>
      ) : files.length === 0 ? (
        <div className="flex h-[400px] items-center justify-center rounded-2xl border border-dashed border-gray-300 bg-gray-50 dark:border-gray-800 dark:bg-gray-900/50">
          <div className="text-center">
            <p className="text-sm text-gray-500 dark:text-gray-400">Your saved files will appear here.</p>
          </div>
        </div>
      ) : (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {files.map((file: any) => (
            <div key={file.id} className="group relative flex flex-col rounded-xl border border-gray-200 bg-white p-4 shadow-sm transition-all hover:shadow-md dark:border-gray-800 dark:bg-gray-900">
              <div className="mb-3 flex items-start justify-between">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600 dark:bg-indigo-900/30 dark:text-indigo-400">
                  {file.file_type === 'pdf' ? <FileText className="h-5 w-5" /> : 
                   ['jpg', 'png', 'jpeg', 'webp'].includes(file.file_type) ? <ImageIcon className="h-5 w-5" /> : 
                   <FileIcon className="h-5 w-5" />}
                </div>
                <div className="flex items-center gap-1">
                  <button
                    onClick={() => {
                      if (confirm('Are you sure you want to delete this file?')) {
                        deleteFile.mutate(file.id);
                      }
                    }}
                    className="rounded-full p-1.5 text-gray-400 transition-colors hover:bg-red-50 hover:text-red-500 dark:hover:bg-red-900/20"
                    title="Delete File"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                  <button
                    onClick={() => toggleFavorite.mutate({ id: file.id, is_favorite: !file.is_favorite })}
                    className={cn(
                      "rounded-full p-1.5 transition-colors",
                      file.is_favorite 
                        ? "text-yellow-500 hover:bg-yellow-50 dark:hover:bg-yellow-900/20" 
                        : "text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800"
                    )}
                  >
                    <Star className="h-4 w-4" fill={file.is_favorite ? "currentColor" : "none"} />
                  </button>
                </div>
              </div>
              <h3 className="mb-1 truncate text-sm font-semibold text-gray-900 dark:text-gray-100" title={file.filename}>
                {file.filename}
              </h3>
              <p className="mb-4 text-xs text-gray-500 dark:text-gray-400">
                Generated by {file.tool_used} • {formatDistanceToNow(new Date(file.created_at), { addSuffix: true })}
              </p>
              <div className="mt-auto pt-3 border-t border-gray-100 dark:border-gray-800">
                <a
                  href={file.url}
                  download={file.filename}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex w-full items-center justify-center gap-2 rounded-lg bg-gray-50 px-3 py-2 text-xs font-medium text-gray-700 transition-colors hover:bg-gray-100 dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-gray-700"
                >
                  <Download className="h-3.5 w-3.5" />
                  Download
                </a>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
